apiVersion: v1
kind: Service
metadata:
  name: fastchat-api-server
  namespace: fastchat
spec:
  selector:
    app: fastchat-api-server
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
