apiVersion: v1
kind: Service
metadata:
  name: fastchat-controller
  namespace: fastchat
spec:
  selector:
    app: fastchat-controller
  ports:
    - port: 21001
      targetPort: 21001
  type: ClusterIP
